// <auto-generated />
using System;
using DeviceApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeviceApi.Migrations
{
    [DbContext(typeof(DeviceDbContext))]
    partial class DeviceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManagementCentral.Shared.Domain.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            Name = "Suzhou"
                        },
                        new
                        {
                            CityId = 2,
                            Name = "Hangzhou"
                        },
                        new
                        {
                            CityId = 3,
                            Name = "Nanjing"
                        },
                        new
                        {
                            CityId = 4,
                            Name = "Seoul"
                        },
                        new
                        {
                            CityId = 5,
                            Name = "Busan"
                        },
                        new
                        {
                            CityId = 6,
                            Name = "Harbin"
                        },
                        new
                        {
                            CityId = 7,
                            Name = "Changsha"
                        },
                        new
                        {
                            CityId = 8,
                            Name = "Jeju"
                        },
                        new
                        {
                            CityId = 9,
                            Name = "Incheon"
                        });
                });

            modelBuilder.Entity("ManagementCentral.Shared.Domain.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("DeviceId");

                    b.HasIndex("CityId");

                    b.ToTable("Device");

                    b.HasData(
                        new
                        {
                            DeviceId = 1,
                            CityId = 1,
                            Date = new DateTime(2015, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = "Weather Sensor"
                        },
                        new
                        {
                            DeviceId = 2,
                            CityId = 2,
                            Date = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = "Weather Sensor"
                        },
                        new
                        {
                            DeviceId = 3,
                            CityId = 3,
                            Date = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Type = "Weather Sensor"
                        },
                        new
                        {
                            DeviceId = 4,
                            CityId = 4,
                            Date = new DateTime(2022, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Type = "Weather Sensor"
                        });
                });

            modelBuilder.Entity("ManagementCentral.Shared.Domain.Device", b =>
                {
                    b.HasOne("ManagementCentral.Shared.Domain.City", "Location")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
